openapi: 3.0.0
info:
  title: trace-cruncher
  description: This is the trace-cruncher API.
  version: 1.0.0
servers:
- url: https://localhost:8088/v1
security:
- BasicAuth: []
paths:
  /system_call:
    get:
      description: Returns a tracing result object of a system call trace of an event
      responses:
        "200":
          description: Successful response
        "404":
          description: The specified tracing resource was not found
    put:
      description: Update or create the specified tracing resource
      responses:
        "201":
          description: Successful response
        "401":
          description: Unauthorized to start or stop trace
    post:
      description: Creates a tracing resource
      responses:
        "201":
          description: Successful response
        "401":
          description: Unauthorized to create tracing resource
    delete:
      description: Remove the specified tracing resource
      responses:
        "200":
          description: Successfully removed tracing resource
        "404":
          description: The specified tracing resource was not found
components:
  schemas: {}
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
