apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: pod-reader
subjects:
- kind: ServiceAccount
  name: pod-reader
  namespace: default
roleRef:
 kind: ClusterRole
 name: pod-reader
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: trace-kube-api
spec:
  selector:
    app: trace-kube-frontend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: trace-kube-node
spec:
  selector:
    app: trace-kube-backend
  clusterIP: None
  clusterIPs:
     - None
  type: ClusterIP
  ports:
   - port: 8080
     targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-kube-api
  labels:
    app: trace-kube-frontend
spec:
  selector:
    matchLabels:
      app: trace-kube-frontend
  template:
    metadata:
      labels:
        app: trace-kube-frontend
    spec:
      serviceAccountName: pod-reader
      automountServiceAccountToken: true
      containers:
      - name: trace-kube
        image: vmware/opensource/trace-kube/tracer-svc:latest
        env:
        - name: TRACE_KUBE_DISCOVERY_POLL
          value: "30"
        - name: TRACE_KUBE_SELECTOR_PODS
          value: "app=trace-kube-backend"
        - name: TRACE_KUBE_SELECTOR_SVCS
          value: "metadata.name=trace-kube-node"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trace-kube-node
spec:
  selector:
    matchLabels:
      app: trace-kube-backend
  template:
    metadata:
      labels:
        app: trace-kube-backend
    spec:
      serviceAccountName: pod-reader
      automountServiceAccountToken: true
      containers:
      - name: trace-kube
        image: vmware/opensource/trace-kube/tracer-node:latest
        env:
        - name: TRACER_PROCFS_PATH
          value: "/host/proc"
        - name: TRACER_SYSFS_PATH
          value: "/host/sys"
        - name: TRACER_RUN_PATHS
          value: "/host/run, /host/var/run"
        - name: TRACER_JEAGER_ENDPOINT
          value: "auto"
        - name: TRACER_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TRACER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
        - mountPath: /host/run
          name: run
        - mountPath: /host/var/run
          name: vrun
        ports:
        - containerPort: 8080
      hostNetwork: false
      hostPID: true
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /run
          type: ""
        name: run
      - hostPath:
          path: /var/run
          type: ""
        name: vrun
